package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ApplitoolsVisualTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ApplitoolsVisualTests")) {
    params {
        expect {
            password("env.APPLITOOLS_API_KEY", "%vault:applitools/api-key%")
        }
        update {
            password("env.APPLITOOLS_API_KEY", "credentialsJSON:22ba65da-83c7-4b6d-b223-aeb6443c69da")
        }
    }

    expectSteps {
        maven {
            name = "Install dependencies"
            goals = "clean install -DskipTests"
            runnerArgs = "-B"
        }
        maven {
            name = "Run Applitools Eyes tests"
            goals = "test"
            runnerArgs = "-Dtest=**/*VisualTest -B"
            param("teamcity.build.failOnErrorMessages", "false")
        }
        script {
            name = "Poll Applitools batch status (optional gate)"
            scriptContent = """
                #!/bin/bash
                set -e
                echo "Batch ID: %env.APPLITOOLS_BATCH_ID%"
                
                # Calls the real "List batch results" API to check for failed/unresolved
                # tests before letting the pipeline proceed to deploy. Requires the batch
                # to be closed (all tests finished) before this check is meaningful.
                # Docs: https://applitools.com/docs/eyes/reference/server-api/batches/list-batch-results
                RESPONSE=${'$'}(curl -s -H "X-Eyes-Api-Key: %env.APPLITOOLS_API_KEY%" \
                  "https://eyes.applitools.com/api/v1/batches/%env.APPLITOOLS_BATCH_ID%?statsOnly=true")
                
                echo "${'$'}RESPONSE"
                
                FAILED=${'$'}(echo "${'$'}RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['statistics']['failed'])")
                UNRESOLVED=${'$'}(echo "${'$'}RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['statistics']['unresolved'])")
                
                if [ "${'$'}FAILED" != "0" ] || [ "${'$'}UNRESOLVED" != "0" ]; then
                  echo "##teamcity[buildStatus status='FAILURE' text='Applitools batch has failed=${'$'}FAILED unresolved=${'$'}UNRESOLVED diffs']"
                  exit 1
                fi
            """.trimIndent()
        }
    }
    steps {
        update<MavenBuildStep>(1) {
            clearConditions()
            goals = "clean test-compile exec:exec@run-the-tests"
            runnerArgs = "B -Dexec.classpathScope=test"
            param("teamcity.build.failOnErrorMessages", "")
            param("teamcity.kubernetes.executor.pull.policy", "")
        }
    }
}
