package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ApplitoolsVisualTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ApplitoolsVisualTests")) {
    params {
        expect {
            password("env.APPLITOOLS_API_KEY", "%vault:applitools/api-key%")
        }
        update {
            password("env.APPLITOOLS_API_KEY", "credentialsJSON:22ba65da-83c7-4b6d-b223-aeb6443c69da")
        }
    }
}
